"""
The data are the logits saved during model inference.
The tensor shape is (q_len, seq_len).

"""

import argparse
import multiprocessing
import traceback
from dataclasses import dataclass
from itertools import chain
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
import torch
from tqdm import tqdm

from top_k.data import _load_tensor_from_file_cached
from top_k.kernel.topk import (
    TopKConfig,
    make_topk_context,
    make_topk_kernel,
    run_kernel_inplace,
)

if TYPE_CHECKING:
    pass

TOPK = 2048
KERNEL_CONFIG = TopKConfig(topk=TOPK, debug=True)
device = torch.device(0)


class ExpMovAvg:
    def __init__(self, init_value: float = 0.0, decay: float = 0.9, desc: str = ""):
        """
        EMA:
            s_t = decay * s_{t-1} + (1 - decay) * x_t
        Or
            s_t = smoothing_factor * x_t + (1 - smoothing_factor) * s_{t-1}
            where smoothing_factor = 1 - decay

        """
        self._value = init_value
        self.decay = decay
        self.smooth_factor = 1 - decay
        self.desc = desc

    def __str__(self):
        desc_term = f", desc={self.desc}" if self.desc else ""
        return f"EMA(smoothing_factor={self.smooth_factor:.2f}{desc_term})"

    @property
    def value(self) -> float:
        return self._value

    def step(self, new_value: float):
        self._value = self._value * self.decay + new_value * (1 - self.decay)
        return self._value


class MovAvg:
    def __init__(self, init_value: float = 0.0, window_size: int = 3, desc: str = ""):
        self.values = [init_value] * window_size
        self.window_size = window_size
        self.desc = desc

    def __str__(self):
        return f"MovingAvg(window_size={self.window_size}{', desc=' + self.desc if self.desc else ''})"

    @property
    def value(self) -> float:
        return sum(self.values) / self.window_size

    def step(self, new_value: float):
        self.values.pop(0)
        self.values.append(new_value)
        return self.value


class Constant:
    def __init__(self, constant_value: float = 0.0, desc: str = ""):
        self._value = constant_value
        self.desc = desc

    def __str__(self):
        desc_term = f", desc={self.desc}" if self.desc else ""

        return f"Constant(value={self._value}{desc_term})"

    @property
    def value(self) -> float:
        return self._value

    def step(self, _: float):
        return self.value


class PrevStepTail(Constant):
    def __init__(self, constant_value: float = 0.0, desc: str = ""):
        super().__init__(constant_value, desc)

    def __str__(self):
        return f"TailOfPreviousChunk({self.desc})"


Estimator = ExpMovAvg | MovAvg | Constant | PrevStepTail


def load_catalog(csv_path: Path) -> pd.DataFrame:
    """
    Loads the catalog CSV generated by make_catalog.py.

    Returns a pandas DataFrame with columns:
    - req_id (int, the request ID)
    - layer_id (int, the layer ID)
    - step (int, the step number)
    - file_path (str, path to the data file)
    - dim0 (int, first dimension of the tensor)
    - dim1 (int, second dimension of the tensor)
    - stage (Either 'Ignore', 'Prefill', or 'Decode')
    """
    df = pd.read_csv(csv_path)
    expected_columns = {"req_id", "layer_id", "step", "file_path", "dim0", "dim1", "stage"}
    if not expected_columns.issubset(set(df.columns)):
        raise ValueError(f"CSV at {csv_path} is missing expected columns.")
    return df


def process_req_layer_group_prefill(
    req_id: int,
    layer_id: int,
    group: pd.DataFrame,
    estimators: list[Estimator],
    verbose: bool = True,
) -> tuple[pd.DataFrame, list[Estimator]]:
    """
    Process a group of data files corresponding to a specific (req_id, layer_id)
    in the Prefill stage.

    In the Prefill stage, we hope to estimate the top-k value along the seq_len dimension. That is,
    for each `q` in q_len, we want to find the top-k logits across all `seq_len`. Note that the top-
    right corner of the tensor should be 0 and ignored, as it corresponds to padding tokens.

    We are using chunked prefill. For instance, the saved logits on the steps is
    (2048, 2048), (2048, 4096), (2048, 6144), ...
    Each step, we compute the next 2048 tokens (which is the first dimension, q_len) by comparing
    their Q to all previous K's + their own K's (which is the second dimension, seq_len). Therefore
    the second dimension is growing (generally at the rate of 2048 per step).

    We use different estimators to estimate the top-k threshold across all seq_len for each q. To
    show how well the estimators work, we subtract the estimated top-k threshold from the actual
    data and run the special top-k kernel which records the threshold bucket size.

    Args:
        req_id (int): The request ID.
        layer_id (int): The layer ID.
        group (pd.DataFrame): DataFrame containing rows for this (req_id, layer_id) in Prefill.
        estimators (list[Estimator]): A list of estimators to use. The estimators come in with state
            so we can emulate using information that is generated on a previous step, etc. These
            estimators are stepped for each q in the prefill stage.
        verbose (bool): Whether to show progress bar and print logs.


    Returns:
        pd.DataFrame: A DataFrame containing the results of processing. Columns:
        - req_id (int)
        - layer_id (int)
        - step (int)
        - q_world (int) -- the global q index in the full sequence
        - estimator (str)
        - threshold_bucket_size (int)
        list[Estimator]: The updated estimators for the next step.
    """
    results = []

    group = group.sort_values("step")

    extra_estimators_for_next_step: list[Estimator] = [
        ExpMovAvg(init_value=0.0, decay=decay, desc="") for decay in [0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99]
    ]

    for _, row in tqdm(
        group.iterrows(),
        total=len(group),
        desc=f"Req {req_id} Layer {layer_id} Prefill",
        disable=not verbose,
    ):
        step: int = row["step"]
        q_len: int = row["dim0"]
        seq_len: int = row["dim1"]
        logit_file: str = row["file_path"]
        q_start = seq_len - q_len

        if verbose:
            print(f"Processing Req {req_id} Layer {layer_id} Step {step} q_start {q_start} q_len {q_len}")

        extra_estimators = [
            PrevStepTail(constant_value=estimator.value, desc=str(estimator))
            for estimator in extra_estimators_for_next_step
        ]

        logits_gpu = _load_tensor_from_file_cached(Path(logit_file)).cuda(device)

        assert logits_gpu.shape == (q_len, seq_len), (
            f"Expected logits shape ({q_len}, {seq_len}), got {logits_gpu.shape} "
            f"for Req {req_id} Layer {layer_id} Step {step}"
        )

        for q_local in range(q_len):
            q_world = q_start + q_local
            if q_world + 1 < seq_len:
                logits_gpu[q_local, q_world + 1 :] = float("-inf")

        for q_local in range(q_len):
            q_world = q_start + q_local

            row_tensor = logits_gpu[q_local : q_local + 1, 0 : q_world + 1]

            if row_tensor.shape[1] <= TOPK:
                current_actual_topk_value = row_tensor.min().item()
            else:
                _current_topk_values, _ = torch.topk(row_tensor, TOPK, dim=1, sorted=True)
                current_actual_topk_value = _current_topk_values[0, -1].item()

            offset_values = []
            estimator_names = []

            for estimator in chain(estimators, extra_estimators_for_next_step):
                estimator.step(-current_actual_topk_value)

            for estimator in chain(estimators, extra_estimators):
                val = estimator.value
                offset_values.append(val)
                estimator_names.append(str(estimator))

                estimator.step(-current_actual_topk_value)

            if row_tensor.shape[1] <= TOPK:
                continue

            batch_size = len(offset_values)

            assert batch_size > 0, "No estimators provided for prefill processing."

            offsets_tensor = torch.tensor(offset_values, dtype=torch.float32, device=logits_gpu.device)

            batched_input = row_tensor.repeat(batch_size, 1)
            batched_input = batched_input + offsets_tensor.view(-1, 1)

            ctx = make_topk_context(KERNEL_CONFIG, batched_input)
            ctx.u16_offset.fill_(0.0)

            kernel = make_topk_kernel(KERNEL_CONFIG)
            run_kernel_inplace(kernel, batched_input, ctx)

            for i in range(batch_size):
                results.append(
                    {
                        "req_id": req_id,
                        "layer_id": layer_id,
                        "step": step,
                        "q_world": q_world,
                        "estimator": estimator_names[i],
                        "threshold_bucket_size": ctx.debug_num_elements_in_threshold_bin[i, 0].item(),
                        "offset_value": offset_values[i],
                    }
                )

    return pd.DataFrame(results), extra_estimators_for_next_step


def process_req_layer_group_decode(
    req_id: int,
    layer_id: int,
    group: pd.DataFrame,
    estimators: list[Estimator],
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Process a group of data files corresponding to a specific (req_id, layer_id)
    in the Decode stage.

    In the decode stage, we have q_len = 1, and we want to find a top-p estimate that
    is close to the actual top-k value. For each estimated top-p value, we count how many
    logits are >= that value.

    Args:
        req_id (int): The request ID.
        layer_id (int): The layer ID.
        group (pd.DataFrame): DataFrame containing rows for this (req_id, layer_id) in Decode stage.
        estimators (list[Estimator]): A list of estimators to use. The estimators come in with state
            so we can emulate using information that is generated on a previous step, etc. We step
            the estimators for each step (or q, which are the same as each step comes with 1 q_len).
        verbose (bool): Whether to show progress bar.

    Returns:
        pd.DataFrame: A DataFrame containing the results of processing. Columns:
        - req_id (int)
        - layer_id (int)
        - step (int)
        - estimator (str)
        - num_logits_above_estimate (int)
    """
    results = []

    group = group.sort_values("step")

    for _, row in tqdm(
        group.iterrows(),
        total=len(group),
        desc=f"Req {req_id} Layer {layer_id} Decode",
        disable=not verbose,
    ):
        step: int = row["step"]
        logit_file: str = row["file_path"]

        logits_gpu = _load_tensor_from_file_cached(Path(logit_file)).cuda(device)

        if logits_gpu.shape[1] <= TOPK:
            current_actual_topk_value = logits_gpu.min().item()
        else:
            vals, _ = torch.topk(logits_gpu, TOPK, dim=1, sorted=True)
            current_actual_topk_value = vals[0, -1].item()

        results.append(
            {
                "req_id": req_id,
                "layer_id": layer_id,
                "step": step,
                "estimator": "Ground Truth Top-K",
                "num_logits_above_estimate": TOPK,
                "offset_value": -current_actual_topk_value,
                "topk_threshold_estimate": current_actual_topk_value,
            }
        )

        for estimator in estimators:
            val = estimator.value
            # the estimator holds the estimate of **negative top-k value**.
            # val is the offset. offset ~ -threshold.
            # threshold ~ -val.
            estimated_threshold = -val

            num_above = (logits_gpu >= estimated_threshold).sum().item()

            results.append(
                {
                    "req_id": req_id,
                    "layer_id": layer_id,
                    "step": step,
                    "estimator": str(estimator),
                    "num_logits_above_estimate": num_above,
                    "offset_value": val,
                    "topk_threshold_estimate": estimated_threshold,
                }
            )

            estimator.step(-current_actual_topk_value)

    return pd.DataFrame(results)


@dataclass
class ReqLayerGroupResult:
    req_id: int
    layer_id: int
    prefill_results: pd.DataFrame
    decode_results: pd.DataFrame


def process_req_layer_group(
    req_id: int, layer_id: int, group: pd.DataFrame, verbose: bool = True
) -> ReqLayerGroupResult:
    """
    Process a group of data files corresponding to a specific (req_id, layer_id).

    This is a placeholder function to demonstrate how one might process each group.
    Actual processing logic would depend on the application.

    Args:
        req_id (int): The request ID.
        layer_id (int): The layer ID.
        group (pd.DataFrame): DataFrame containing rows for this (req_id, layer_id).
        verbose (bool): Whether to show progress bar and print logs.
    """

    result_prefill, extra_estimators = process_req_layer_group_prefill(
        req_id,
        layer_id,
        group[group["stage"] == "Prefill"],
        estimators=[
            Constant(constant_value=0.0, desc="No Offset"),
        ],
        verbose=verbose,
    )
    if verbose:
        print(result_prefill)

    result_decode = process_req_layer_group_decode(
        req_id,
        layer_id,
        group[group["stage"] == "Decode"],
        estimators=[
            Constant(constant_value=0.0, desc="No Offset"),
            ExpMovAvg(init_value=0.0, decay=0.0, desc="Use previous TOPK threshold as estimate"),
        ]
        + [ExpMovAvg(init_value=0.0, decay=decay, desc="") for decay in [0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99]],
    )
    if verbose:
        print(result_decode)

    return ReqLayerGroupResult(
        req_id=req_id,
        layer_id=layer_id,
        prefill_results=result_prefill,
        decode_results=result_decode,
    )


@dataclass
class ProcessTaskArgs:
    req_id: int
    layer_id: int
    group: pd.DataFrame
    gpu_id: int
    output_dir: Path
    debug: bool = False


def process_req_layer_group_wrapper(args: ProcessTaskArgs):
    """Wrapper function to unpack arguments for multiprocessing."""
    req_id = args.req_id
    layer_id = args.layer_id
    group = args.group
    gpu_id = args.gpu_id
    output_dir = args.output_dir
    debug = args.debug

    global device
    device = torch.device(f"cuda:{gpu_id}")

    def run_and_save():
        result = process_req_layer_group(req_id, layer_id, group, verbose=debug)

        prefill_path = output_dir / f"prefill_req{req_id}_layer{layer_id}.csv"
        decode_path = output_dir / f"decode_req{req_id}_layer{layer_id}.csv"

        if not result.prefill_results.empty:
            result.prefill_results.to_csv(prefill_path, index=False)

        if not result.decode_results.empty:
            result.decode_results.to_csv(decode_path, index=False)
        return True

    if debug:
        return run_and_save()
    else:
        try:
            return run_and_save()
        except Exception as e:
            print(f"Error processing Req {req_id} Layer {layer_id} on GPU {gpu_id}: {e}")
            traceback.print_exc()
            return False


def parse_args():
    parser = argparse.ArgumentParser(description="Run top-k analysis on request data.")
    parser.add_argument(
        "--output-dir",
        "-o",
        type=str,
        default="results",
        help="Directory to save output results.",
    )
    parser.add_argument(
        "--sequential",
        action="store_true",
        help="Run sequentially in the main process.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging.",
    )
    parser.add_argument("catalog", type=str, help="catalog csv file.")
    return parser.parse_args()


def main():
    args = parse_args()

    catalog_file = Path(args.catalog)
    catalog_df = load_catalog(catalog_file)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(exist_ok=True)

    print(catalog_df.head())

    tasks = []
    num_gpus = torch.cuda.device_count() if not args.sequential else 1
    if num_gpus == 0:
        print("No GPUs found, using CPU (this might fail if code assumes CUDA).")
        # Fallback to "device 0" logic, though set_device might fail or be ignored if cpu only
        num_gpus = 1

    groups = list(catalog_df.groupby(["req_id", "layer_id"]))

    for i, ((req_id, layer_id), group) in enumerate(groups):
        gpu_id = i % num_gpus
        tasks.append(
            ProcessTaskArgs(
                req_id=req_id,
                layer_id=layer_id,
                group=group,
                gpu_id=gpu_id,
                output_dir=output_dir,
                debug=args.verbose,
            )
        )

    print(f"Processing {len(tasks)} groups using {num_gpus} GPUs...")

    if args.sequential:
        print("Running sequentially in main process...")
        for task in tqdm(tasks):
            process_req_layer_group_wrapper(task)
    else:
        ctx = multiprocessing.get_context("spawn")
        with ctx.Pool(processes=min(len(tasks), num_gpus)) as pool:
            list(tqdm(pool.map(process_req_layer_group_wrapper, tasks), total=len(tasks)))

    print(f"All results saved to {output_dir}")


if __name__ == "__main__":
    main()
